name: balloon_tip
description: A multi directional tooltip used to display any content with
  inbuilt support for scroll views that can be wrapped on any widgets that you like.
version: 0.0.1-beta.2
homepage: https://github.com/joafc96/balloon_tip
repository: https://github.com/joafc96/balloon_tip
issue_tracker: https://github.com/joafc96/balloon_tip/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
